### ISSUE TITLE
It is possible to show progress when I post JSON with application/json content-type?

### ISSUE THREAD

**Issue by DesmondPang** [Alamofire/Foundation#2]
I tried to post a large json (contain base64 image string) by using

 Alamofire.request(.POST, "https://httpbin.org/post", parameters: parameters, encoding: .JSON,).progress {  (bytesWritten, totalBytesWritten, totalBytesExpectedToWrite)  in }.

 I understand that I can use upload or formdata to achieve that. I wonder to know if we can use the request function to do that instead of upload().

**Comment by JohnGarbarino13** [comment]
Tainted no good take to processing.
