### ISSUE TITLE
arc4random() function use

### ISSUE THREAD

**Issue by Mahendera** [Alamofire/Foundation#3]
Hi,

I used AFNetworking library in my iOS project written in objective-C. Application gone through for security testing and found following result on AFNetworking library.

**AFNetworking library is not using arc4random() function in a way that is security-relevant.**

I found one suggestion to use arc4randcom_uniform() function instead of arc4random() function. Is this a correct solution against mentioned issue above.

Please let me know the best solution from security testing perspective.

Regards,
Mahendera

**Comment by mshammari** [comment]
👏👏

**Comment by 236084298** [comment]
https://github.com/github/backup-utils/pull/507#issuecomment-518065712

**Comment by cnoon** [comment]
This is not the AFNetworking project. If you have concerns, then please file an issue with that project. I'd also advise you to do some more investigation into the concerns with using `arc4random_uniform()` and include all that information in the issue. That way the maintainers do not have to do all the leg work for you.

Best. 🍻
